productService:
  image: gayatri1702/product-service:latest
  replicas: 2
  port: 8000

orderService:
  image: gayatri1702/order-service:latest
  replicas: 2
  port: 8001

userService:
  image: gayatri1702/user-service:latest
  replicas: 2
  port: 8002