apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort

  selector:
    app: product-service

  ports:
    - port: {{ .Values.productService.port }}
      targetPort: {{ .Values.productService.port }}